/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CA_App": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "ContactApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ContactLambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CourseData": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MAILGUN_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Scraper": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ScraperState": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}