/// <reference types="Cypress" />

context('Actions', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
  })

  it('can add and remove courses', () => {
    // Add COMP1511
    cy.get('#course-selection-autocomplete').type('comp1511{enter}')
    cy.get('#course-display').should('contain.text', 'COMP1511')

    // Add COMP1521
    cy.get('#course-selection-autocomplete').type('comp15')
    cy.get('[data-cy=autocomplete-option]')
      .first().should('contain.text', 'COMP1521')
      .click()
    cy.get('#course-display')
      .should('contain.text', 'COMP1511')
      .should('contain.text', 'COMP1521')

    // Search for courses starting with "M", select MATH1231 (requires clicking 'see more')
    cy.get('#course-selection-autocomplete').type('m')
    cy.get('[data-cy=autocomplete-option]')
      .last().should('contain.text', 'See more results...')
      .click()
    cy.get('[data-cy=autocomplete-option]')
      .contains('MATH1231')
      .click()
    cy.get('#course-display').should('contain.text', 'MATH1231')

    // Can remove a course
    cy.get('#course-display')
      .find('[data-cy=remove-course]')
      .eq(1)
      .click()
    cy.get('#course-display')
      .should('not.contain.text', 'COMP1521')
      .should('contain.text', 'COMP1511')
      .should('contain.text', 'MATH1231')
  })

  it('can add/edit/remove a custom event', () => {
    cy.get('[data-cy=create-custom-event]')
      .click()
    cy.get('[data-cy=custom-event-name]')
      .type('A personal event name')
    cy.get('[data-cy=custom-event-duration]')
      .click()
    cy.get('[data-cy=custom-event-duration-item]')
      .eq(4)
      .click()
    cy.get('[data-cy=custom-event-day]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-day-item]')
      .first()
      .click()
    cy.get('[data-cy=custom-event-time]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-time-item]')
      .first()
      .click()
    cy.get('[data-cy=custom-event-day]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-day-item]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-time]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-time-item]')
      .last()
      .click()
    cy.get('[data-cy=custom-event-submit]')
      .should('contain.text', 'Add')
      .click()

    cy.get('#course-display')
      .should('contain.text', 'A personal event name')

    // Clicking add new event gives clean dialog
    cy.get('[data-cy=create-custom-event]')
      .click()
    cy.get('[data-cy=custom-event-name]')
      .find('input')
      .should('have.value', '')
    cy.get('[data-cy=custom-event-duration]')
      .find('input')
      .should('have.value', '1')
    cy.get('[data-cy=custom-event-day]')
      .should('have.length', 1)
      .should('have.value', '')
    cy.get('[data-cy=custom-event-submit]')
      .should('contain.text', 'Add')
    cy.get('[data-cy=close-dialog]')
      .click()

    // Clicking edit event loads expected values
    cy.get('[data-cy=edit-custom]')
      .click()
    cy.get('#custom-event-title')
      .should('exist')
    cy.get('[data-cy=custom-event-name]')
      .find('input')
      .should('have.value', 'A personal event name')
      .clear()
      .type('New name for event')
    cy.get('[data-cy=custom-event-duration]')
      .find('input')
      .should('have.value', '2.5')
    cy.get('[data-cy=custom-event-day]')
      .should('have.length', 3)
      .first()
      .find('input')
      .should('have.value', 'M')
    cy.get('[data-cy=custom-event-time]')
      .eq(0)
      .find('input')
      .should('have.value', '8')
    cy.get('[data-cy=custom-event-time]')
      .eq(1)
      .find('input')
      .should('have.value', '20')
    cy.get('[data-cy=custom-event-submit]')
      .should('contain.text', 'Save')
      .click()

    cy.get('#course-display')
      .should('not.contain.text', 'A personal event name')
      .should('contain.text', 'New name for event')


    cy.get('#course-display')
      .find('[data-cy=remove-course]')
      .click()
  })
})
