/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_CONTACT_ENDPOINT: string
  readonly VITE_DATA_ROOT_URI: string
  readonly VITE_CAMPUS: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}